Install MPI by default; always check_env; consistent tab formatting
mesh-adaptation/docs pull request #68
Opened 2024-11-23 17:24 UTC by jwallwork23

I was having an issue running MPI parallel tests locally because of conflicting MPI builds.

This PR changes the installation process so that existing MPI builds are not picked up by default. It also ensures that the `check_env` command is always run.

2024-12-08 09:16 UTC, ddundo commented
I thought about what we discussed during the meeting about skipping `check_env` during `make install`. Can't a user just do `yes | make install` to skip all prompts?

2024-12-08 10:54 UTC, jwallwork23 commented
> I thought about what we discussed during the meeting about skipping `check_env` during `make install`. Can't a user just do `yes | make install` to skip all prompts?

True, although I think that's a little less clear than having a specific recipe.

2024-12-11 06:33 UTC, ddundo requested changes
I tested this with #77 and it looks good, apart from one change in the Makefile. Although the cache errors are hit there as well in Goalie

2024-12-11 08:50 UTC, jwallwork23 commented on install/Makefile
> +install: check_env
Oops! I think what I was thinking of was this:
```suggestion
install: check_env install_no_chk
```

2024-12-11 09:02 UTC, ddundo commented on install/Makefile
> +install: check_env
Nice! Makes sense :)

2024-12-11 14:52 UTC, ddundo approved these changes

2024-12-11 14:52 UTC, ddundo commented on .github/workflows/test_firedrake_install.yml
> +  group: 'install_firedrake_test-${{ github.ref }}'
```suggestion
  group: 'test_firedrake_install-${{ github.ref }}'
```
Forgot to rename this to match filename, sorry

2024-12-11 14:52 UTC, ddundo commented on .github/workflows/test_firedrake_install.yml
> +          curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/fix-mpi-install/install/petsc_configure_options.txt
```suggestion
          curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/Makefile
          curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/petsc_configure_options.txt
```
Change to main branch before merging

2024-12-11 17:35 UTC, merged